.\" (C) Copyright 2021 Anuradha Weeraman <anuradha@debian.org>,
.TH SRAIN 1 "October  1 2021"
.SH NAME
srain \- graphical IRC client based on GTK+
.SH SYNOPSIS
.B srain
[\fI\,OPTIONS\/\fR]... [\fI\,URL\/\fR]...
.SH DESCRIPTION
.B Srain
is a modern IRC client that is based on a GTK+ GUI.
.SH OPTIONS
.PP
.B Help Options:
.TP
.B \-h, \-\-help
Show help options
.TP
.B \-\-help\-all
Show all help options
.TP
.B \-\-help\-gapplication
Show GApplication options
.TP
.B \-\-help\-gtk
Show GTK+ Options
.PP
.B Application Options:
.TP
.B \-v, \-\-version
Show version information
.TP
.B \-a, \-\-no\-auto
Don't auto connect to servers
.TP
.B \-\-display=DISPLAY
X display to use
.SH FILES
.PP
.TP
.B /etc/srain/builtin.cfg
System-wide configuration file
.TP
.B ~/.config/srain/srain.cfg
User-specific overrides of the configuration
.SH COPYRIGHT
.PP
2021, Shengyu Zhang. Licensed under GPL-3+ with OpenSSL exception.
